# coding: utf-8
import logging

import requests
from django.conf import settings
from django.core.cache import cache
from keycloak import KeycloakOpenID

from kobo.apps.oc_tenant_auth.adapter import (
    _cached_client_secret,
    _cached_realm_name,
)
from kpi.models import AssetSnapshot

LOGGER = logging.getLogger(__name__)

_REQUEST_TIMEOUT_SECONDS = 5
_TOKEN_CACHE_TTL_BUFFER_SECONDS = 30
_TOKEN_CACHE_KEY_PREFIX = 'oc:generatexform_token'


def decorate_snapshot_with_study_designer_preview(snapshot, request):
    """
    Best-effort enhancement: replace `snapshot`'s XML (already generated by
    the normal formpack/pyxform path) with the decorated XForm XML
    form-service would produce for the same survey, so Form Designer's
    preview matches Study Designer's. Never raises: on any failure,
    `snapshot`'s XML (already set by the normal creation path) is left
    untouched.
    """
    try:
        decorated_xml = _fetch_decorated_xml(snapshot, request)
    except Exception as exc:
        LOGGER.warning(
            'decorate_snapshot_with_study_designer_preview: failed to fetch '
            'decorated XML for snapshot %s: %s',
            snapshot.uid,
            exc,
            exc_info=True,
        )
        return

    if not decorated_xml:
        return

    try:
        AssetSnapshot.objects.filter(pk=snapshot.pk).update(xml=decorated_xml)
    except Exception as exc:
        LOGGER.warning(
            'decorate_snapshot_with_study_designer_preview: failed to '
            'persist decorated XML for snapshot %s: %s',
            snapshot.uid,
            exc,
            exc_info=True,
        )
        return

    # Keep the in-memory instance in sync with what was just persisted, so
    # callers reusing `snapshot` after this call see the decorated XML too.
    snapshot.xml = decorated_xml


def _fetch_decorated_xml(snapshot, request):
    realm_name = _cached_realm_name(request)
    token = _cached_client_credentials_token(realm_name)
    if not token:
        LOGGER.warning(
            'generateXform: no client-credentials token available for '
            'realm %s, snapshot %s',
            realm_name,
            snapshot.uid,
        )
        return None

    xlsx_io = snapshot.to_xlsx_io()
    response = requests.post(
        f'{settings.OC_BUILD_URL}/form-service/api/xlsForm/generateXform',
        files={
            'file': (
                f'{snapshot.uid}.xlsx',
                xlsx_io,
                'application/vnd.openxmlformats-officedocument' '.spreadsheetml.sheet',
            ),
        },
        data={'rewrite_media_references': 'false'},
        headers={'Authorization': f'Bearer {token}'},
        timeout=_REQUEST_TIMEOUT_SECONDS,
    )

    if response.status_code != 200:
        LOGGER.warning(
            'generateXform returned %s for snapshot %s',
            response.status_code,
            snapshot.uid,
        )
        return None

    xml = response.text
    if not xml or not xml.strip():
        LOGGER.warning(
            'generateXform returned an empty body for snapshot %s',
            snapshot.uid,
        )
        return None

    if not xml.lstrip().startswith(('<?xml', '<h:')):
        LOGGER.warning(
            'generateXform returned a malformed (non-XML) body for ' 'snapshot %s',
            snapshot.uid,
        )
        return None

    return xml


def _cached_client_credentials_token(realm_name):
    key = f'{_TOKEN_CACHE_KEY_PREFIX}:{realm_name}'
    token = cache.get(key)
    if token:
        return token

    client_secret = _cached_client_secret(realm_name)
    if not client_secret:
        # No client secret configured for this realm: requesting a token
        # would only fail, and would do so on every preview attempt. Skip
        # the call rather than raise the same error repeatedly.
        LOGGER.warning(
            'no client secret configured for realm %s; skipping '
            'client-credentials token request',
            realm_name,
        )
        return None

    keycloak_openid = KeycloakOpenID(
        server_url=f'{settings.KEYCLOAK_AUTH_URI}/auth/',
        realm_name=realm_name,
        client_id=settings.KEYCLOAK_CLIENT_ID,
        client_secret_key=client_secret,
        timeout=_REQUEST_TIMEOUT_SECONDS,
    )
    token_response = keycloak_openid.token(grant_type='client_credentials')
    access_token = token_response['access_token']
    expires_in = int(token_response.get('expires_in', 60))
    ttl = max(expires_in - _TOKEN_CACHE_TTL_BUFFER_SECONDS, 1)
    cache.set(key, access_token, ttl)
    return access_token
